### ISSUE TITLE
Cross platform easy installation?

### ISSUE THREAD

**Issue by IAMtheIAM** [google/ios-webkit-debug-proxy#220] opened 2017-08-17 17:22 UTC
Just wondering how come this can't be shipped via NPM prebuilt to work cross platform? Currently it is very cumbersome to have to create scripts to install run powershell, install scoop, then install this program via scoop. On a dev team this needs to be automated. Now try making it cross platform automated, even more troubles.

Any possibility of cross platform prebuilt binaries shipped on NPM? [Issue 136](https://github.com/google/ios-webkit-debug-proxy/issues/136) said this was going to happen but then the issue is closed with no follow up since april

**Comment by artygus** [comment] 2017-08-17 18:30
duplicate of #136, please use existing issue

I've no time to work on npm package right now

**Closed by artygus** 2017-08-17 18:30 UTC
