### ISSUE TITLE
Connects to iPad but shows blank console in browser

### ISSUE THREAD

**Issue by donrhummy** [google/ios-webkit-debug-proxy#119] opened 2015-10-02 06:03 UTC
I am able to connect to the iPad and see a message like:

    Connected :9222 to Don's iPad (378c2c788...)

I then go into my web browser to http://localhost:9222 and I correctly see the link for the web page listed, but after clicking it, t's just a blank page with a gray bar and search box. Refreshing (on both the iPad and the Chrome desktop browser) does nothing.

I know the page prints output because going to it in Chrome shows the output to the console.

The page:

	<!DOCTYPE html>
	<html>
		<head></head>
		<body>
			<script type="text/javascript">
				console.log( "yes" );
			</script>
		</body>
	</html>

Also, when I show devtools in Chrome on the inspector page, there's no errors.

What could be wrong?

**iPad iOS 8.4**
**Ubuntu 14.10**

**Comment by marcvangend** [comment] 2015-10-02 13:30
Duplicate of issue #86. In particular comment https://github.com/google/ios-webkit-debug-proxy/issues/86#issuecomment-73438873 fixed it for me.

**Comment by donrhummy** [comment] 2015-10-02 18:08
@marcvangend Thank you, using "http://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html" AND clearing the cached app (it uses a manifest file) made it work for me. Why isn't this in the documentation for this project?

**Comment by marcvangend** [comment] 2015-10-02 19:27
It seems that the software is evolving rapidly and that there are different ways to solve the same problem. What works for you and me may not work for everyone else, so that makes it hard to write good documentation I guess.

That said; it's open source software, so you can help make it better. Feel free to fork the project, improve the documentation in README.md and and submit a pull request.

**Comment by donrhummy** [comment] 2015-10-02 22:23
As soon as I have free time, I'll take a look at what it's doing and see if I cna offer any help.

I'll also write some documentation for compiling/upgrading to the latest version of libimobiledevice as that's missing (requires 1.2+) on a lot of Linux computers (judging from the many issues found online and my own experience) and the instructions online were inadequate. Might help.

**Comment by paulirish** [comment] 2015-10-05 00:36
I've updated the readme a bunch today, so hopefully that helps. Similarly, I put up #120 to propose changing the default frontend. 

All PRs to this project are very welcome!

**Comment by paulirish** [comment] 2015-10-05 00:37
and @marcvangend thanks very much for helping out on these issue threads!

**Closed by paulirish** 2015-10-05 00:36 UTC

**Comment by donrhummy** [comment] 2015-10-05 16:53
@paulirish can you also add to the documentation that because it's an offline web app, people may need to clear the app's data from their browser's cache to see the changes?
