### ISSUE TITLE
ios-webkit-debug-proxy get random disconnects from Safari on physical device with error

### ISSUE THREAD

**Issue by joaopedroms22** [google/ios-webkit-debug-proxy#143] opened 2016-06-01 21:53 UTC
Hi,
I'm running  some tests in parallel on several iOS device at once.
I'm running the tests through Selenium Grid.
My config is this:

Appium - 1.5.2
iOS devices - from 8.4.1 to 9.3.2 versions
ios webkit debug proxy - 1.6
OS X El Capitan - 10.11.4
Xcode - 7.3.1 (7D1014)

I already double checked if my dependencies are all up date.
I checked this dependencies:
libusb - 1.0.20
libplist - 1.12
usbmuxd - 1.0.10
libimobiledevice - 1.2.0
ideviceinstaller - 1.1.0

My Web Inspector is enabled.
I've already read all the issues related to this topic, already tried all the solution i've read there and no one solved my problems with the random proxys disconnect from the devices.
Already tested another i-w-d-p (this one https://github.com/jchuong/ios-webkit-debug-proxy) and still facing the same issues.

Safari launcher always gets open on all devices, and then he open the Apple page, but when needs go to the page that I gave on the tests sometimes goes, sometimes not, and when will not is due to proxy already disconnected from the device.

The problem is this like some other related before:

```
> Connected :27755 to iPhone 5S  (device udid)

> Unknown app_id PID:2149
> Invalid message _rpc_applicationSentListing: <dict>
> 	<key>WIRApplicationIdentifierKey</key>
> 	<string>PID:2149</string>
> 	<key>WIRListingKey</key>
> 	<dict>
> 	</dict>
> </dict>
> Disconnected :27755 from iPhone 5S  (device udid)
> 
```

And sometimes like this:

```
> Connected :27754 to iPhone 5C (device did)

> Unknown app_id PID:1645
> Invalid message _rpc_applicationSentListing: <dict>
> 	<key>WIRApplicationIdentifierKey</key>
> 	<string>PID:1645</string>
> 	<key>WIRListingKey</key>
> 	<dict>
> 		<key>1</key>
> 		<dict>
> 			<key>WIRPageIdentifierKey</key>
> 			<integer>1</integer>
> 			<key>WIRURLKey</key>
> 			<string>http://www.apple.com/</string>
> 			<key>WIRTitleKey</key>
> 			<string>Apple</string>
> 			<key>WIRTypeKey</key>
> 			<string>WIRTypeWeb</string>
> 		</dict>
> 	</dict>
> </dict>
> Disconnected :27754 from iPhone 5C (device did)
> 
```
Is this issue already fixed or its a issue for iOS 9.x versions? 

Regards

**Comment by artygus** [comment] 2016-06-23 22:56
looks like you're using old version, did you build it from sources?

**Comment by joaopedroms22** [comment] 2016-06-27 15:16
hi @artygus ,

yes I builted from source, I've tried everything with no luck in any.
Some tip?

Regards

**Comment by SrinivasanTarget** [comment] 2016-07-30 11:18
@artygus We at ```Appium``` [https://github.com/appium/appium/blob/master/bin/ios-webkit-debug-proxy-launcher.js] suggests our users to use ```ios-webkit-debug-proxy``` for safari automation on iOS real devices. I see many of the issues are related to random disconnect of  ```ios-webkit-debug-proxy```.I see ```ios-webkit-debug-proxy``` has a tremendous use case behind web automation support.Would be great if you prioritize this issue and get it sorted.

**Comment by skumar1122** [comment] 2016-08-01 21:23
Hello @artygus

Srinivas , FYI 

I used before ,iwdp like this : 
ios_webkit_debug_proxy -c UDID:27755 -d and have seen devices disconnected error.

And I started using iwdp from appium bin : 
/bin/ios-webkit-debug-proxy-launcher.js -c udid:27753 -d 
it seems to work great where you cannot get disconnected any devices but sometimes when ur running multiple tests its gets hung up and only can see apple.com in safari launcher. so then I have to close safari launcher or restart iwdp kit or use PM2 tool to restart it.
I Used PM2 tool its great but it is not helping me in auto connecting to my devices, rather I have to use : restart pm2 "app id" and then it connects to the device. 

Logs:
[debug] [iOS] Executing iOS command 'setUrl'
[debug] [iOS] Attempting to set url 'my url'
[debug] [RemoteDebugger] Navigating to new URL: my url
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Page.navigate","...
[debug] [RemoteDebugger] Receiving WebKit data: {"result":{},"id":1}
[debug] [RemoteDebugger] Found handler for message '1'
[debug] [RemoteDebugger] Received page navigated message: {"result":{},"id":1}
[debug] [RemoteDebugger] Waiting for dom...
[debug] [RemoteDebugger] Page loaded, verifying whether ready
[debug] [RemoteDebugger] Checking document readyState
[debug] [RemoteDebugger] Sending javascript command (function (){ return docume...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...

Thanks

**Comment by SrinivasanTarget** [comment] 2016-08-02 08:35
@skumar1122 I'm aware of the alternative solutions you have provided.But still those are not stable at times.That's the reason i have raised it here.

**Comment by nghiadhd** [comment] 2016-08-18 11:22
@artygus 
Seem I found a root cause

In Normal behavior, after sending "_rpc_forwardGetListing", the ios-webkit-debug-proxy expects that it will receive 2 messages

```
[_rpc_applicationSentListing:] <dict>
	<key>WIRApplicationIdentifierKey</key>
	<string>PID:258</string>
	<key>WIRListingKey</key>
	<dict>
	</dict>
</dict>

[_rpc_applicationConnected:] <dict>
	<key>WIRApplicationIdentifierKey</key>
	<string>PID:9827</string>
	<key>WIRIsApplicationProxyKey</key>
	<true/>
	<key>WIRApplicationNameKey</key>
	<string></string>
	<key>WIRApplicationBundleIdentifierKey</key>
	<string>com.apple.WebKit.WebContent</string>
	<key>WIRIsApplicationActiveKey</key>
	<integer>1</integer>
	<key>WIRHostApplicationIdentifierKey</key>
	<string>PID:258</string>
</dict>
```

However Abnormal behavior, the ios-webkit-debug-proxy got 2 same messages and then got a message with unknown app_id

```
[_rpc_applicationSentListing:] <dict>
	<key>WIRApplicationIdentifierKey</key>
	<string>PID:194</string>
	<key>WIRListingKey</key>
	<dict>
	</dict>

</dict>

[_rpc_applicationSentListing:] <dict>
	<key>WIRApplicationIdentifierKey</key>
	<string>PID:194</string>
	<key>WIRListingKey</key>
	<dict>
	</dict>
</dict>

[_rpc_applicationSentListing:] <dict>
	<key>WIRApplicationIdentifierKey</key>
	<string>PID:197</string>
	<key>WIRListingKey</key>
	<dict>
		<key>1</key>
		<dict>
			<key>WIRPageIdentifierKey</key>
			<integer>1</integer>
			<key>WIRURLKey</key>
			<string>http://demoqa.com/contact/</string>
			<key>WIRTitleKey</key>
			<string>Contact | Demoqa</string>
			<key>WIRTypeKey</key>
			<string>WIRTypeWeb</string>
		</dict>
	</dict>
</dict>
```

Currently, I workaround it by resend "_rpc_forwardGetListing" if Unknown App_id and it works like a charm

Logs

OK: https://gist.github.com/nghiadhd/4f6bd63c5440828083d839d053fb1d68#file-webkit_proxy_ok
NG: https://gist.github.com/nghiadhd/6b6fee1c87ff4482e8e0a0a2d4f86ebf#file-webkit_proxy_ng

**Comment by artygus** [comment] 2016-08-18 17:30
Hi @nghiadhd thanks for the observations! I'll take a closer look this weekend

**Comment by artygus** [comment] 2016-08-18 17:42
@nghiadhd or in case you've already implemented it you're welcome to open a PR

**Comment by artygus** [comment] 2016-08-21 23:31
was able to reproduce the issue, currently working on the fix based on what nghiadhd solution

**Comment by SrinivasanTarget** [comment] 2016-08-21 23:35
Sounds good

**Comment by nghiadhd** [comment] 2016-08-22 04:04
I have just made PR
I fixed for my local and confirm it works on 6 devices in parallel, you can refer my solution, merge or just close it if you found the better way

https://github.com/google/ios-webkit-debug-proxy/pull/155

**Comment by artygus** [comment] 2016-08-22 18:23
@nghiadhd merged now, thanks! 👍

**Closed by artygus** 2016-08-22 18:23 UTC

**Comment by SrinivasanTarget** [comment] 2016-08-22 18:33
Thanks @nghiadhd. Also @artygus may i know when this will be available in ```brew```.

**Comment by artygus** [comment] 2016-08-22 18:36
@SrinivasanTarget you can get in brew with `--HEAD` flag

**Comment by SrinivasanTarget** [comment] 2016-09-15 14:55
Hi @artygus I'm getting No head is defined error.

**Comment by artygus** [comment] 2016-09-15 20:34
@SrinivasanTarget a couple of days ago updated version of ios-webkit-debug-proxy was published to brew, please try `brew update && brew upgrade ios-webkit-debug-proxy`

**Comment by mayureshshirodkar** [comment] 2016-10-03 18:55
@artygus @SrinivasanTarget 
On iPhone 6S with iOS 10.0, I am initially able to connect to the iPhone via ios debug webkit.
But on trying to search for a Webview the connection breaks.

Same scenario **works well on iOS 9.3.5**.

Dependency versions:
OS X El Capitan - 10.11.6
ios-webkit-debug-proxy 1.7
libimobiledevice HEAD-00424f4
libplist 1.12
libusb 1.0.20
usbmuxd 1.0.10 1.0.10_1
ideviceinstaller 1.1.0_2


Logs:
$ ios_webkit_debug_proxy -c <UDID>:27753
Connected :27753 to Mayuresh’s iPhone (UDID)
Unknown app_id PID:456
Invalid message _rpc_applicationSentListing: <dict>
	<key>WIRApplicationIdentifierKey</key>
	<string>PID:456</string>
	<key>WIRListingKey</key>
	<dict>
		<key>3</key>
		<dict>
			<key>WIRPageIdentifierKey</key>
			<integer>3</integer>
			<key>WIRTitleKey</key>
			<string>JSContext</string>
			<key>WIRTypeKey</key>
			<string>WIRTypeJavaScript</string>
		</dict>
	</dict>
</dict>
Disconnected :27753 from Mayuresh’s iPhone (UDID)

Logs seems similar to once posted by @joaopedroms22

**Comment by mayureshshirodkar** [comment] 2016-10-16 14:27
@artygus @SrinivasanTarget  Any Updates on this? 
Do I need to update my dependency ?
