### ISSUE TITLE
Everything works fine, but the Dev Tools Page is empty and doesn't contain Safari Information

### ISSUE THREAD

**Issue by tralpha** [google/ios-webkit-debug-proxy#86] opened 2014-12-21 15:32 UTC
I'm using an iPhone 5s with a Safari browser, together with a Mac 10.10.1.

I could install the ios webkit debug proxy and get it working. It can detect my phone and everything, but however when I copy the link of the available website for debugging into a new Chrome page and try debugging, I simply get a blank DevTools page, and I can't find and manipulate the DOM from the Safari browser on my iPhone.

Could anyone tell me what's wrong with this? Is there anything I'm doing wrong? Please let me know.

Thanks!
Ralph

**Comment by schickling** [comment] 2015-01-06 14:41
+1

**Comment by montoya-azul** [comment] 2015-01-07 18:11
Same here :(

**Comment by montogeek** [comment] 2015-01-07 18:34
Use http://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html

**Comment by jfrumar** [comment] 2015-01-10 07:22
That's still not working for me :(

**Comment by seanwash** [comment] 2015-01-15 01:10
I'm getting the same blank page by using chrome-devtools://devtools/bundled/devtools.html. Looks like the proxy sees the ios simulator fine, but the inspector is blank.

**Comment by TeddyRux** [comment] 2015-01-15 16:16
:+1:

**Comment by hcentelles** [comment] 2015-01-16 17:36
:+1:

**Comment by confile** [comment] 2015-01-21 00:46
+1 I have to same problem as @tralpha I always get an empty page in the chrome dev tools. Also with @montogeek  http://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html it does not connect.

Is there something else to do?

**Comment by steffimueller** [comment] 2015-01-21 01:02
I have the same problem. Could not connect.

**Comment by steffimueller** [comment] 2015-01-21 01:03
@montogeek Are you able to connect to your device?

**Comment by montogeek** [comment] 2015-01-21 06:28
Yes, I was able.

**Comment by confile** [comment] 2015-01-21 13:59
@wrightt Is google working on a fix for this issue?

**Comment by mandx** [comment] 2015-01-22 18:37
Same here, after compiling and running it on Ubuntu 14.04. (installing instructions from [this thread](https://github.com/google/ios-webkit-debug-proxy/issues/66#issuecomment-53903278)) Latest Chrome stable from Google's repos shows the inspector blank (there isn't even a `window` global in the console) and no errors at all. Tried with Firefox's Valence/WebIDE and it also shows no error, but the connection doesn't go through.

**Comment by mikejoyceio** [comment] 2015-01-24 10:26
Having the same issue as the OP.

**Comment by horsson** [comment] 2015-01-26 15:24
same issue here.

**Comment by richardkeen** [comment] 2015-01-27 16:47
I worked around this by downloading Chromium 37 for Mac from here: http://sourceforge.net/projects/osxportableapps/files/Chromium/

**Comment by osuka** [comment] 2015-01-27 20:46
can confirm this works with latest Chrome (40) and Safari w/ iOS 8.1 if launched like:
```
ios_webkit_debug_proxy -f http://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html
```
Works fine but it's crazy slow. Still, miles better than debugging via remote Safari.

**Comment by montogeek** [comment] 2015-01-27 20:48
Thanks!

**Comment by mcmilwj** [comment] 2015-01-28 16:28
Worked for me @osuka .. thanks!

**Comment by mandx** [comment] 2015-01-29 22:10
@osuka I can confirm it works with that frontend on Ubuntu 14.04, and also sluggish slow.

**Comment by pmeenan** [comment] 2015-01-30 13:57
It's a newer version than from Chrome 27 but WebPagetest has an embedded
version of the timeline code as well.  If you access the github version
through the rawgit CDN interface (MaxCDN) it should be a lot faster than
the appspot URL:
https://cdn.rawgit.com/WPO-Foundation/webpagetest/WebPageTest-2.16/www/chrome/inspector-20140603/devtools.html

If that doesn't work I can see about putting an older version up as well
(maybe in a dedicated repository).

**Comment by jfrumar** [comment] 2015-02-03 20:57
When I load up http://localhost:9222/ and then click the link for my connected device, I got:

404. That's an error.

The requested URL /devtools/devtools.html?host=localhost:9222&page=1 was not found. Invalid frontend URL?

**Comment by GingerBear** [comment] 2015-02-08 23:20
saw a [comment](http://stackoverflow.com/questions/11361822/debug-ios-67-mobile-safari-using-the-chrome-devtools?rq=1#comment43062053_16903378) on stackoverflow, seems to be working (fast but still buggy) using `ws` parameter like `chrome-devtools://devtools/bundled/devtools.html?ws=localhost:9222/devtools/page/1` with default start.

**Comment by aerohit** [comment] 2015-02-11 16:13
I was getting a blank page on chrome dev tools. I tried the [chrome-devtools://devtools/bundled/devtools.html?ws=localhost:9222/devtools/page/1](chrome-devtools://devtools/bundled/devtools.html?ws=localhost:9222/devtools/page/1) as suggested by **GingerBear** above and managed to connect finally. 


But I keep losing the connection. I get a 'websocket_closed' message on the devtools and the following error on the terminal: 

Invalid message _rpc_applicationUpdated

**Comment by GingerBear** [comment] 2015-02-12 18:50
@aerohit I am guessing newer devtools change its debug protocol, so this project can no longer correctly translate from safari's debug protocol to devtools'. 

The version of devtool used be the default (18.0.1025.74) works well. You can see the version in history of a file https://github.com/google/ios-webkit-debug-proxy/commit/97244edb2c3b499007be5eeaf36623ee06e53864#diff-5ec77c8336660a306cae07d0bd49757dL208

**Comment by wrightt** [comment] 2015-03-20 21:52
Yeah, I think

**Comment by wrightt** [comment] 2015-03-20 22:02
Oops, I clicked "Close" by mistake!

Anyways, yes, there seem to be two issues here:
1. I need to add the trivial "_rpc_applicationUpdated" handler, and
2. Chrome's inspector UI no longer supports the latest MobileSafari's DevTools -- we'd have to fix the Chromium https://chromium.googlesource.com/chromium/blink/+/master/Source/devtools/front_end/

**Comment by paulirish** [comment] 2015-04-09 07:06
Chrome and Safari have now diverged a bit with the debugger protocol.  I haven't looked into how much, but I suspect it isn't a big gap. It's likely quite fixable.

###  protocol status

#### current Chrome DevTools protocol:
https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/devtools/protocol.json

(and a handy viewer for it: http://chromedevtools.github.io/debugger-protocol-viewer/ )


#### current Safari Inspector protocol:
http://trac.webkit.org/browser/trunk/Source/JavaScriptCore/inspector/protocol

Mozilla maintains a snapshot of the protocols in ios7 and ios8: https://github.com/mozilla/valence/tree/master/protocol-docs

### get involved

It'd be very valuable for someone to author a protocol compat layer to allow the io7 and ios8 protocols to map back to modern Chrome protocol. Then you could use whatever's in your browser.

If you want to hack around.. try [inspecting the inspector](http://stackoverflow.com/a/12291163/89484) to see whats up with the empty devtools page or [sniffing out the websocket connection](https://developer.chrome.com/devtools/docs/debugger-protocol#alpha) to view the raw data

:arrow_right:  **Ping me if you'd like to get involved in this.**

**Comment by artygus** [comment] 2015-04-09 09:19
@paulirish I would like to help

**Comment by niftylettuce** [comment] 2015-05-05 16:19
Thanks @richardkeen, your [suggestion](https://github.com/google/ios-webkit-debug-proxy/issues/86#issuecomment-71681600) worked for me.

**Comment by wrightt** [comment] 2015-05-05 18:40
Sounds good to me!  @paulirish, I've added you as a project admin, so please feel free to coordinate.

**Comment by dangelov** [comment] 2015-05-11 17:43
fwiw @GingerBear 's suggestion for using `ws` works for me

**Comment by evelynriossf** [comment] 2015-05-21 02:22
May 20th.. I'm getting the same problem with the white screen in Chrome 43. @GingerBear 's suggestion to use chrome-devtools://devtools/bundled/devtools.html?ws=localhost:9222/devtools/page/1 works for me.

**Comment by grglaz** [comment] 2015-07-02 09:47
running ios_webkit_debug_proxy -f http://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html

and browsing with http://localhost:9222/devtools/devtools.html?ws=localhost:9222/devtools/page/1

works for me but communication is soooo slow...

**Comment by shmdhussain** [comment] 2015-07-13 15:08
@GingerBear:  ur suggestion is working..thanks..but I am not able to inspect webview application pages. is anybody facing this issue?

**Comment by auchenberg** [comment] 2015-07-13 15:27
@grglaz @shmdhussain Which build of ``ios-webkit-debug-proxy`` are you running with? I [committed](https://github.com/google/ios-webkit-debug-proxy/commit/996024083a31a0e589f677f7cc5840d1337d357a) a changed to update the chrome devtools url, so the WS querystring is correct.

**Comment by shmdhussain** [comment] 2015-07-13 15:48
@auchenberg : Just now i installed the ios-webkit-debug-proxy (i think v1.5) in OSX 10.10 and chrome 43

**Comment by auchenberg** [comment] 2015-07-13 15:51
@shmdhussain Alrighty, then it's unrelated to my change. Never mind :)

**Comment by shmdhussain** [comment] 2015-07-13 15:56
@auchenberg : so will it work normally as "http://localhost:9222/devtools/devtools.html?ws=localhost:9222/devtools/page/1" instead of "chrome-devtools://devtools/bundled/devtools.html?ws=localhost:9222/devtools/page/1"?

Could you please help me in how to debug UIWebview native ios app, i am not able to do so. Thanks in advance.

**Comment by foobartel** [comment] 2015-07-13 16:05
@shmdhussain @auchenberg For me v1.5 only works with this url:
chrome-devtools://devtools/bundled/devtools.html?ws=localhost:9222/devtools/page/1 

The link from http://localhost:9222/ for the first iOS device is 
http://localhost:9222/devtools/devtools.html?ws=localhost:9222/devtools/page/1 though, and that only shows a white page with a grey bar at the top and some Apple SLA comment in the source.

**Comment by shmdhussain** [comment] 2015-07-13 16:12
@foobartel : are you able to inspect native webview app? see my screenshot for http://localhost:9222/devtools/devtools.html?ws=localhost:9222/devtools/page/1 
![screen shot 2015-07-13 at 9 33 35 pm](https://cloud.githubusercontent.com/assets/4039657/8654421/d1210320-29a7-11e5-8caa-4d5c1fbe2352.png)

screenshot for chrome-devtools://devtools/bundled/devtools.html?ws=localhost:9222/devtools/page/1

![screen shot 2015-07-13 at 9 35 40 pm](https://cloud.githubusercontent.com/assets/4039657/8654452/05abc68e-29a8-11e5-9149-9faec9b8f917.png)

**Comment by kcbanner** [comment] 2015-07-29 20:12
I am specifically interested in the profiling capabilities. Since Safari 7, the JavaScript CPU profiler is missing. I'd like to use the Chrome devtools to run CPU profiles on iOS devices, since the only way to run  a CPU profiler currently is to downgrade to OS X 10.8 and use Safari 6. I can use ios_webkit_debug_proxy to debug my webview/safari with the Chrome Canary bundled dev tools, but sadly the profiling tools to not work.

**Comment by animator013** [comment] 2015-09-17 11:41
From chrome ver. 45 url 
```
chrome-devtools://devtools/bundled/devtools.html?ws=localhost:9222/devtools/page/1
``` 
no longer works for me.

I used this instead:

```
chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1
```

Hope it helps someone.

**Comment by nikoloza** [comment] 2015-09-18 03:30
Running

    ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html

worked for me. *Note:* `inspector.html` at the end instead of `devtools.html`

**Comment by paulirish** [comment] 2015-09-21 22:18
Yes, this is a permanent change. For anyone uses the bundled inspector you should be using it via `inspector.html`, as the two above comments indicate.

Sorry for the breakage here.

**Comment by donrhummy** [comment] 2015-10-02 18:09
What's the earliest version of Chrome that has this bundled inspector? 
"ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html"

**Comment by artygus** [comment] 2015-10-03 10:33
@kcbanner check this out https://github.com/artygus/webkit-webinspector, I extracted webkit's webinspector so there's no need to downgrade to safari 6 anymore

**Comment by desmondtam** [comment] 2015-10-16 23:49
I'm able to see the requests, but the timings are mis-translated I think.  Does anybody else see something similar?
![pasted_image_10_16_15__3_40_pm](https://cloud.githubusercontent.com/assets/15131388/10554865/5115fb94-741c-11e5-9f67-291094471293.jpg)

**Comment by leftdevel** [comment] 2015-10-26 14:43
@animator013. Your solution works for me, thanks!

**Closed** 2017-01-19 20:42 UTC

**Comment by netpoetica** [comment] 2017-03-13 14:56
Is it expected that one should see the console.logs from their client application in the Inspector?

**Comment by artygus** [comment] 2017-03-13 16:06
hi @netpoetica absolutely, but there're more and more issues with dev tools, please check out https://github.com/google/ios-webkit-debug-proxy#devtools-note
