### ISSUE TITLE
cannot recognize multi iOS simulators  when i run two simulator instances!

### ISSUE THREAD

**Issue by wendywenwen** [google/ios-webkit-debug-proxy#213] opened 2017-07-05 13:24 UTC
I open two two simulator instances(iphone 7 and iphone 6s , both iOS 10.3), and my xcode is 8.3.3 , when I run ios_webkit_debug_proxy , the device list only include physical devices and only one simulator, so I want to know if the ios_webkit_debug_proxy  tool support multi iOS simulators?
![image](https://user-images.githubusercontent.com/20834531/27866681-d94e5cbc-61c9-11e7-981d-45f2970df49c.png)

**Comment by artygus** [comment] 2017-07-05 13:41
I believe only one webinspector instance at a time can be exposed for debugging from simulator. So the answer is no, I can't find any official docs on this topic though. Similar unsolved issue https://github.com/facebook/FBSimulatorControl/issues/12. I'm closing this now as multiple simulator instances running on same machine was never supported and Safari can also see only one simulator

**Closed by artygus** 2017-07-05 13:41 UTC

**Comment by artygus** [comment] 2018-02-16 08:31
afaik the problem is webinspectord service for simulator starts on only one port which is 27753, I'm not sure but if you enable javascript debugging in only one simulator and turn off in others could be the way to debug specific one
