### ISSUE TITLE
Cleanup for ios-Webkit-debug-Proxy after the Test Execution

### ISSUE THREAD

**Issue by AppiumIOSRuser** [google/ios-webkit-debug-proxy#322] opened 2019-08-01 11:38 UTC
Is there any cleanup command for the  ios-Webkit-debug-Proxy. We execute almost 1000 test cases in different test suites on 4 ios devices iPad,IPhone6,iPhone8 and iPhoneX. But currently after every test suite execution I have to restart the ios-Webkit-debug-Proxy to get memory space.

I am executing tests from MAC Mini which has 16GB RAM. I have to execute 3 Test suites consecutively. But after the first test suite execution the memory is fully occupied ios-Webkit-debug-Proxy is not releasing the memory even after the test execution completed(Observed from the Activity Monitor in MAC ). So I have to restart  ios-Webkit-debug-Proxy for all four devices before I start the second test Suite. Please let me know if there any command to do this cleanup automatically from code after every test execution?

I am starting the  ios-Webkit-debug-Proxy from .sh file like below
ios_webkit_debug_proxy  -c UDID1:Port1 -d
ios_webkit_debug_proxy  -c UDID2:Port2 -d
ios_webkit_debug_proxy  -c UDID3:Port3 -d
ios_webkit_debug_proxy  -c UDID4:Port4 -d

ios-webkit-debug-proxy Version Used v1.8.4.

**Comment by artygus** [comment] 2019-09-03 19:34
hi @AppiumIOSRuser, it's interesting, must be some memory leaks, is it easy reproducible with 1 device?

**Comment by artygus** [comment] 2020-03-05 11:04
closing since no reply from OP

**Closed by artygus** 2020-03-05 11:04 UTC
