### ISSUE TITLE
Iphone XS Max not detected by ios_webkit_debug_proxy "Unable to attach [...] inspector"

### ISSUE THREAD

**Issue by Nafiros** [google/ios-webkit-debug-proxy#285] opened 2018-11-12 15:05 UTC
When I start ios_webkit_debug_proxy with iphone linked by cable to the PC (windows 10) I get this error
"No iPhone found, is it plugged in?: No error"
"Unable to attach 00008020001D0D592E88002E inspector"

 
but the iphone is well connected to the PC and trust it.

Any ideas ?

thank

**Comment by Nafiros** [comment] 2018-11-12 16:22
Hi ! Sure i'm using the 1.8.2 it's working on iphone 7 on iOS 12 but it's not working on iphone XS Max on iOS 12.

**Comment by artygus** [comment] 2018-11-12 16:37
I see, the problem seems to be related to https://github.com/libimobiledevice/libimobiledevice/issues/706

in the meantime, could you please try running

```
ios_webkit_debug_proxy -u 00008020-001d0d592e88002e
```

**Comment by Nafiros** [comment] 2018-11-12 16:45
The same error pop again on the cmd with this command :/

**Comment by artygus** [comment] 2018-11-12 16:48
do you have latest itunes installed?

**Comment by Nafiros** [comment] 2018-11-12 16:54
Yes i installed it today

**Comment by artygus** [comment] 2018-11-12 19:50
what if you supply udid in the upper case

```
ios_webkit_debug_proxy -u 00008020-001D0D592E88002E
```

**Comment by artygus** [comment] 2018-11-15 09:17
I found the cause of the issue, it was exactly problem mentioned above, pushed changes to master, but now I'm experiencing strange behaviour, I'll delay release until I get to the bottom of it

**Comment by artygus** [comment] 2018-11-23 14:40
should be fixed in 1.8.3, check out releases page

**Closed by artygus** 2018-11-23 14:40 UTC

**Comment by Nubzor** [comment] 2019-01-13 12:41
@artygus it seems I have a similar problem with iPhone Xs. I am on Ubuntu 18.10, using the original Apple's cable and 1.8.3 ios-webkit-debug-proxy. 

`
$ idevice_id -l
`
returns 
`
00008020000368601108002E
`

but afterall there is an error

`
Listing devices on :9221
`
`No iPhone found, is it plugged in?: Operation now in progress`
`Unable to attach 00008020-000368601108002E inspector`

Am I doing smth wrong?

**Comment by artygus** [comment] 2019-01-13 15:18
hi @Nubzor can you confirm you're using latest version of libimobiledevice and usbmuxd (built from master)?

**Comment by AngelOnFira** [comment] 2019-04-15 20:35
@artygus I'm getting the same problem as @Nubzor, same conditions (Ubuntu 18.04.2, iPhone XR, original apple cable). My versions of libimobiledevice and usbmuxd are as follows

```
$ ios_webkit_debug_proxy -V
ios_webkit_debug_proxy 1.8.3
Built with libimobiledevice v1.2.1, libplist v2.0.0

$ idevice_id -l   
00008020000A6CD62E81002E

$ sudo apt-get install usbmuxd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
usbmuxd is already the newest version (1.1.0-2ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
```

and the output

```
$ ios_webkit_debug_proxy
Listing devices on :9221
No iPhone found, is it plugged in?: Operation now in progress
Unable to attach 00008020-000A6CD62E81002E inspector
```

**Comment by artygus** [comment] 2019-04-16 07:27
@AngelOnFira you also need to have libusbmuxd/usbmuxd build from master

**Comment by Nubzor** [comment] 2019-04-16 08:20
@artygus Sorry for the late response, I am more than sure I haven't receive any activity notification under this issue. 

Most likely, I had the newest version of libimobiledevice and usbmuxd back then. I'd have to repeat the steps nowadays to be sure, however, I gave up with this way of debugging. 

For the sake of leaving the world in better shape than I found it, I'll check it and post an update here in a few days.

**Comment by php4umagento** [comment] 2019-11-15 11:53
Same problem for me 18.04 with iphone running latest IOS

```
 ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html -u 00008030-00092DEE0230802E
No device found, is it plugged in?
Unable to attach 00008030-00092DEE0230802E inspector
```

`idevice_id -l
0000803000092DEE0230802E`
