### ISSUE TITLE
Blank inspector page on iOS 13

### ISSUE THREAD

**Issue by unstablereality** [google/ios-webkit-debug-proxy#349] opened 2020-01-14 16:50 UTC
OSX Version: 10.14.6
ios_webkit_debug_proxy: 1.8.5
libimobiledevice: 1.2.1
libplist: 2.1.0
iOS Version: 11.4 (working), 13.1 (not working)

Continuation of https://github.com/google/ios-webkit-debug-proxy/issues/348. Tested using both built in inspector and using @artygus' Safari webkit-inspector. Both do not display any elements or any other information from the phone. Was able to verify normal functionality with an older iPhone running iOS 11.4. 

Example of empty Safari webkit-inspector failing
![image](https://user-images.githubusercontent.com/660602/72363959-54571980-36bb-11ea-9f52-8f0a9537423e.png)

debug output from webkit-inspector failure
```wi.recv_packet[419]:
 00 00 01 9F 62 70 6C 69 73 74 30 30 D2 01 02 03 14 5A 5F  ....bplist00.....Z_
 5F 61 72 67 75 6D 65 6E 74 5A 5F 5F 73 65 6C 65 63 74 6F  _argumentZ__selecto
 72 D2 04 05 06 07 5F 10 1B 57 49 52 41 70 70 6C 69 63 61  r....._..WIRApplica
 74 69 6F 6E 49 64 65 6E 74 69 66 69 65 72 4B 65 79 5D 57  tionIdentifierKey]W
 49 52 4C 69 73 74 69 6E 67 4B 65 79 57 50 49 44 3A 32 31  IRListingKeyWPID:21
 35 D1 08 09 51 31 D5 0A                                   5...Q1..
 0B 0C 0D 0E 0F 10 11 12 13 5B 57 49 52 54 69 74 6C 65 4B  .........[WIRTitleK
 65 79 5A 57 49 52 54 79 70 65 4B 65 79 59 57 49 52 55 52  eyZWIRTypeKeyYWIRUR
 4C 4B 65 79 5F 10 14 57 49 52 50 61 67 65 49 64 65 6E 74  LKey_..WIRPageIdent
 69 66 69 65 72 4B 65 79 5F 10 1A 57 49 52 43 6F 6E 6E 65  ifierKey_..WIRConne
 63 74 69 6F 6E 49 64 65 6E 74 69 66 69 65 72 4B 65 79 56  ctionIdentifierKeyV
 47 6F 6F 67 6C 65 5A 57 49 52 54 79 70 65 57 65 62 5F 10  GoogleZWIRTypeWeb_.
 37 68 74 74 70 73 3A 2F 2F 77 77 77 2E 67 6F 6F 67 6C 65  7https://www.google
 2E 63 6F 6D 2F 3F 63 6C 69 65 6E 74 3D 73 61 66 61 72 69  .com/?client=safari
 26 63 68 61 6E 6E 65 6C 3D 69 70 68 6F 6E 65 5F 62 6D 10  &channel=iphone_bm.
 01 5F 10 24 46 43 36 30 43 41 46 41 2D 31 31 45 41 2D 34  ._.$FC60CAFA-11EA-4
 39 42 37 2D 42 46 34 35 2D 36 45 30 46 33 44 31 43 33 36  9B7-BF45-6E0F3D1C36
 39 36 5F 10 1C 5F 72 70 63 5F 61 70 70 6C 69 63 61 74 69  96_.._rpc_applicati
 6F 6E 53 65 6E 74 4C 69 73 74 69 6E 67 3A 00 08 00 0D 00  onSentListing:.....
 18 00 23 00 28 00 46 00 54 00 5C 00 5F 00 61 00 6C 00 78  ..#.(.F.T.\._.a.l.x
 00 83 00 8D 00 A4 00 C1 00 C8 00 D3 01 0D 01 0F 01 36 00  .................6.
 00 00 00 00 00 02 01 00 00 00 00 00 00 00 15 00 00 00 00  ...................
 00 00 00 00 00 00 00 00 00 00 01 55                       ...........U```

**Comment by artygus** [comment] 2020-01-14 16:51
duplicate of #348

**Closed by artygus** 2020-01-14 16:51 UTC

**Comment by unstablereality** [comment] 2020-01-14 16:53
@artygus Please help me. The solution you suggested is not working for me and I am attempting to solve it but I don't know how to proceed. I can't get this working under iOS 13 and it isn't clear from the README what exactly I should do other than try another inspector.

**Comment by artygus** [comment] 2020-01-14 16:57
To make it clear, this utility is just handles proxying parts of things, i.e. exposing it's API interface through websockets. It has nothing to do with devtools or incompatibility of their internal protocols. Please don't open same issues.

**Comment by artygus** [comment] 2020-01-14 17:02
@unstablereality did you try https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter? iOS 13 support landed recently https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/pull/177

**Comment by unstablereality** [comment] 2020-01-14 17:55
@artygus I tried that and got a very similar result. I got the same error as https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/179 and https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/176 when I attempted to load the debugger. 

I also tried using the `wdp_client.js` file included in your examples and it wouldn't cause the phone to navigate to Google. It produces some normal-looking output, but the phone doesn't do anything. I did verify that I could run the example successfully using the known working phone. 

Output of `wdp_client.js`
```open ws://localhost:9222/devtools/page/1
connected
send {"id": 1, "method": "Page.navigate", "params":{"url": "http://www.google.com"}}
recv {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"page-6","type":"page"}}}
disconnected
```

Error from `wdp_client.js`

debug output from running `wdp_client.js`
```ss.accept server=5 new_client=8
ss.add_fd(8)
ss.recv fd=8 len=238
ws.recv[238]:
 47 45 54 20 2F 64 65 76 74 6F 6F 6C 73 2F 70 61 67 65 2F  GET /devtools/page/
 31 20 48 54 54 50 2F 31 2E 31 0D 0A                       1 HTTP/1.1..
 53 65 63 2D 57 65 62 53 6F 63 6B 65 74 2D 56 65 72 73 69  Sec-WebSocket-Versi
 6F 6E 3A 20 31 33 0D 0A                                   on: 13..
 53 65 63 2D 57 65 62 53 6F 63 6B 65 74 2D 4B 65 79 3A 20  Sec-WebSocket-Key:
 6A 64 52 6E 30 54 64 33 2B 59 69 4B 6D 51 75 48 48 6E 59  jdRn0Td3+YiKmQuHHnY
 33 51 41 3D 3D 0D 0A                                      3QA==..
 43 6F 6E 6E 65 63 74 69 6F 6E 3A 20 55 70 67 72 61 64 65  Connection: Upgrade
 0D 0A                                                     ..
 55 70 67 72 61 64 65 3A 20 77 65 62 73 6F 63 6B 65 74 0D  Upgrade: websocket.
 0A                                                        .
 53 65 63 2D 57 65 62 53 6F 63 6B 65 74 2D 45 78 74 65 6E  Sec-WebSocket-Exten
 73 69 6F 6E 73 3A 20 70 65 72 6D 65 73 73 61 67 65 2D 64  sions: permessage-d
 65 66 6C 61 74 65 3B 20 63 6C 69 65 6E 74 5F 6D 61 78 5F  eflate; client_max_
 77 69 6E 64 6F 77 5F 62 69 74 73 0D 0A                    window_bits..
 48 6F 73 74 3A 20 6C 6F 63 61 6C 68 6F 73 74 3A 39 32 32  Host: localhost:922
 32 0D 0A                                                  2..
 0D 0A                                                     ..
wi.send_packet[347]:
 00 00 01 57 62 70 6C 69 73 74 30 30 D2 01 03 02 04 5A 5F  ...Wbplist00.....Z_
 5F 73 65 6C 65 63 74 6F 72 5F 10 18 5F 72 70 63 5F 66 6F  _selector_.._rpc_fo
 72 77 61 72 64 53 6F 63 6B 65 74 53 65 74 75 70 3A 5A 5F  rwardSocketSetup:Z_
 5F 61 72 67 75 6D 65 6E 74 D5 05 07 09 0B 0D 06 08 0A     _argument.........
 0C 0E 5F 10 1A 57 49 52 43 6F 6E 6E 65 63 74 69 6F 6E 49  .._..WIRConnectionI
 64 65 6E 74 69 66 69 65 72 4B 65 79 5F 10 24 31 31 30 37  dentifierKey_.$1107
 42 34 46 43 2D 41 43 44 38 2D 34 46 31 37 2D 42 33 33 43  B4FC-ACD8-4F17-B33C
 2D 31 33 39 37 32 33 42 37 33 42 45 45 5F 10 1B 57 49 52  -139723B73BEE_..WIR
 41 70 70 6C 69 63 61 74 69 6F 6E 49 64 65 6E 74 69 66 69  ApplicationIdentifi
 65 72 4B 65 79 57 50 49 44 3A 32 31 35 5F 10 15 57 49 52  erKeyWPID:215_..WIR
 41 75 74 6F 6D 61 74 69 63 61 6C 6C 79 50 61 75 73 65 08  AutomaticallyPause.
 5F 10 14 57 49 52 50 61 67 65 49 64 65 6E 74 69 66 69 65  _..WIRPageIdentifie
 72 4B 65 79 10 01 5C 57 49 52 53 65 6E 64 65 72 4B 65 79  rKey..\WIRSenderKey
 5F 10 24 39 36 32 33 44 31 42 41 2D 37 31 35 36 2D 34 43  _.$9623D1BA-7156-4C
 30 35 2D 42 31 39 35 2D 31 41 43 41 46 38 31 41 45 30 35  05-B195-1ACAF81AE05
 43 00 08 00 0D 00 18 00 33 00 3E 00 49 00 66 00 8D 00 AB  C.......3.>.I.f....
 00 B3 00 CB 00 CC 00 E3 00 E5 00 F2 00 00 00 00 00 00 02  ...................
 01 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 00 00 00  ...................
 00 00 00 00 01 19                                         ......
ws.sending_upgrade[138]:
 48 54 54 50 2F 31 2E 31 20 31 30 31 20 57 65 62 53 6F 63  HTTP/1.1 101 WebSoc
 6B 65 74 20 50 72 6F 74 6F 63 6F 6C 20 48 61 6E 64 73 68  ket Protocol Handsh
 61 6B 65 0D 0A                                            ake..
 55 70 67 72 61 64 65 3A 20 57 65 62 53 6F 63 6B 65 74 0D  Upgrade: WebSocket.
 0A                                                        .
 43 6F 6E 6E 65 63 74 69 6F 6E 3A 20 55 70 67 72 61 64 65  Connection: Upgrade
 0D 0A                                                     ..
 53 65 63 2D 57 65 62 53 6F 63 6B 65 74 2D 41 63 63 65 70  Sec-WebSocket-Accep
 74 3A 20 75 43 34 64 6C 48 45 57 39 52 39 71 32 53 36 49  t: uC4dlHEW9R9q2S6I
 39 43 64 54 39 4C 6D 59 76 49 55 3D 0D 0A                 9CdT9LmYvIU=..
 0D 0A                                                     ..
ss.recv fd=9 len=4
wi.recv[4]:
 00 00 01 51                                               ...Q
ss.recv fd=9 len=337
wi.recv[337]:
 62 70 6C 69 73 74 30 30 D2 01 02 03 0A                    bplist00.....
 5A 5F 5F 61 72 67 75 6D 65 6E 74 5A 5F 5F 73 65 6C 65 63  Z__argumentZ__selec
 74 6F 72 D3 04 05 06 07 08 09 5F 10 11 57 49 52 44 65 73  tor......._..WIRDes
 74 69 6E 61 74 69 6F 6E 4B 65 79 5F 10 11 57 49 52 4D 65  tinationKey_..WIRMe
 73 73 61 67 65 44 61 74 61 4B 65 79 5F 10 1B 57 49 52 41  ssageDataKey_..WIRA
 70 70 6C 69 63 61 74 69 6F 6E 49 64 65 6E 74 69 66 69 65  pplicationIdentifie
 72 4B 65 79 5F 10 24 39 36 32 33 44 31 42 41 2D 37 31 35  rKey_.$9623D1BA-715
 36 2D 34 43 30 35 2D 42 31 39 35 2D 31 41 43 41 46 38 31  6-4C05-B195-1ACAF81
 41 45 30 35 43 4F 10 5D 7B 22 6D 65 74 68 6F 64 22 3A 22  AE05CO.]{"method":"
 54 61 72 67 65 74 2E 74 61 72 67 65 74 43 72 65 61 74 65  Target.targetCreate
 64 22 2C 22 70 61 72 61 6D 73 22 3A 7B 22 74 61 72 67 65  d","params":{"targe
 74 49 6E 66 6F 22 3A 7B 22 74 61 72 67 65 74 49 64 22 3A  tInfo":{"targetId":
 22 70 61 67 65 2D 36 22 2C 22 74 79 70 65 22 3A 22 70 61  "page-6","type":"pa
 67 65 22 7D 7D 7D 57 50 49 44 3A 32 31 35 5F 10 19 5F 72  ge"}}}WPID:215_.._r
 70 63 5F 61 70 70 6C 69 63 61 74 69 6F 6E 53 65 6E 74 44  pc_applicationSentD
 61 74 61 3A 00 08 00 0D 00 18 00 23 00 2A 00 3E 00 52 00  ata:.......#.*.>.R.
 70 00 97 00 F7 00 FF 00 00 00 00 00 00 02 01 00 00 00 00  p..................
 00 00 00 0B 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01  ...................
 1B                                                        .
wi.recv_packet[341]:
 00 00 01 51 62 70 6C 69 73 74 30 30 D2 01 02 03 0A        ...Qbplist00.....
 5A 5F 5F 61 72 67 75 6D 65 6E 74 5A 5F 5F 73 65 6C 65 63  Z__argumentZ__selec
 74 6F 72 D3 04 05 06 07 08 09 5F 10 11 57 49 52 44 65 73  tor......._..WIRDes
 74 69 6E 61 74 69 6F 6E 4B 65 79 5F 10 11 57 49 52 4D 65  tinationKey_..WIRMe
 73 73 61 67 65 44 61 74 61 4B 65 79 5F 10 1B 57 49 52 41  ssageDataKey_..WIRA
 70 70 6C 69 63 61 74 69 6F 6E 49 64 65 6E 74 69 66 69 65  pplicationIdentifie
 72 4B 65 79 5F 10 24 39 36 32 33 44 31 42 41 2D 37 31 35  rKey_.$9623D1BA-715
 36 2D 34 43 30 35 2D 42 31 39 35 2D 31 41 43 41 46 38 31  6-4C05-B195-1ACAF81
 41 45 30 35 43 4F 10 5D 7B 22 6D 65 74 68 6F 64 22 3A 22  AE05CO.]{"method":"
 54 61 72 67 65 74 2E 74 61 72 67 65 74 43 72 65 61 74 65  Target.targetCreate
 64 22 2C 22 70 61 72 61 6D 73 22 3A 7B 22 74 61 72 67 65  d","params":{"targe
 74 49 6E 66 6F 22 3A 7B 22 74 61 72 67 65 74 49 64 22 3A  tInfo":{"targetId":
 22 70 61 67 65 2D 36 22 2C 22 74 79 70 65 22 3A 22 70 61  "page-6","type":"pa
 67 65 22 7D 7D 7D 57 50 49 44 3A 32 31 35 5F 10 19 5F 72  ge"}}}WPID:215_.._r
 70 63 5F 61 70 70 6C 69 63 61 74 69 6F 6E 53 65 6E 74 44  pc_applicationSentD
 61 74 61 3A 00 08 00 0D 00 18 00 23 00 2A 00 3E 00 52 00  ata:.......#.*.>.R.
 70 00 97 00 F7 00 FF 00 00 00 00 00 00 02 01 00 00 00 00  p..................
 00 00 00 0B 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01  ...................
 1B                                                        .
ws.sending_frame[95]:
 81 5D 7B 22 6D 65 74 68 6F 64 22 3A 22 54 61 72 67 65 74  .]{"method":"Target
 2E 74 61 72 67 65 74 43 72 65 61 74 65 64 22 2C 22 70 61  .targetCreated","pa
 72 61 6D 73 22 3A 7B 22 74 61 72 67 65 74 49 6E 66 6F 22  rams":{"targetInfo"
 3A 7B 22 74 61 72 67 65 74 49 64 22 3A 22 70 61 67 65 2D  :{"targetId":"page-
 36 22 2C 22 74 79 70 65 22 3A 22 70 61 67 65 22 7D 7D 7D  6","type":"page"}}}
ss.recv fd=8 len=85
ws.recv[85]:
 81 CF 04 2F 81 7C 7F 0D E8 18 26 15 A1 4D 28 0F A3 11 61  .../.|....&..M(...a
 5B E9 13 60 0D BB 5C 26 7F E0 1B 61 01 EF 1D 72 46 E6 1D  [..`..\&...a...rF..
 70 4A A3 50 24 0D F1 1D 76 4E EC 0F 26 15 FA 5E 71 5D ED  pJ.P$...vN..&..^q].
 5E 3E 0F A3 14 70 5B F1 46 2B 00 F6 0B 73 01 E6 13 6B 48  ^>...p[.F+...s...kH
 ED 19 2A 4C EE 11 26 52 FC                                ..*L..&R.
ws.recv_frame[85]:
 81 CF 04 2F 81 7C 7F 0D E8 18 26 15 A1 4D 28 0F A3 11 61  .../.|....&..M(...a
 5B E9 13 60 0D BB 5C 26 7F E0 1B 61 01 EF 1D 72 46 E6 1D  [..`..\&...a...rF..
 70 4A A3 50 24 0D F1 1D 76 4E EC 0F 26 15 FA 5E 71 5D ED  pJ.P$...vN..&..^q].
 5E 3E 0F A3 14 70 5B F1 46 2B 00 F6 0B 73 01 E6 13 6B 48  ^>...p[.F+...s...kH
 ED 19 2A 4C EE 11 26 52 FC                                ..*L..&R.
wi.send_packet[422]:
 00 00 01 A2 62 70 6C 69 73 74 30 30 D2 01 03 02 04 5A 5F  ....bplist00.....Z_
 5F 73 65 6C 65 63 74 6F 72 5F 10 17 5F 72 70 63 5F 66 6F  _selector_.._rpc_fo
 72 77 61 72 64 53 6F 63 6B 65 74 44 61 74 61 3A 5A 5F 5F  rwardSocketData:Z__
 61 72 67 75 6D 65 6E 74 D5 05 07 09 0B 0D 06 08 0A        argument.........
 0C 0E 5F 10 1A 57 49 52 43 6F 6E 6E 65 63 74 69 6F 6E 49  .._..WIRConnectionI
 64 65 6E 74 69 66 69 65 72 4B 65 79 5F 10 24 31 31 30 37  dentifierKey_.$1107
 42 34 46 43 2D 41 43 44 38 2D 34 46 31 37 2D 42 33 33 43  B4FC-ACD8-4F17-B33C
 2D 31 33 39 37 32 33 42 37 33 42 45 45 5F 10 1B 57 49 52  -139723B73BEE_..WIR
 41 70 70 6C 69 63 61 74 69 6F 6E 49 64 65 6E 74 69 66 69  ApplicationIdentifi
 65 72 4B 65 79 57 50 49 44 3A 32 31 35 5F 10 14 57 49 52  erKeyWPID:215_..WIR
 50 61 67 65 49 64 65 6E 74 69 66 69 65 72 4B 65 79 10 01  PageIdentifierKey..
 5C 57 49 52 53 65 6E 64 65 72 4B 65 79 5F 10 24 39 36 32  \WIRSenderKey_.$962
 33 44 31 42 41 2D 37 31 35 36 2D 34 43 30 35 2D 42 31 39  3D1BA-7156-4C05-B19
 35 2D 31 41 43 41 46 38 31 41 45 30 35 43 5F 10 10 57 49  5-1ACAF81AE05C_..WI
 52 53 6F 63 6B 65 74 44 61 74 61 4B 65 79 4F 10 4F 7B 22  RSocketDataKeyO.O{"
 69 64 22 3A 20 31 2C 20 22 6D 65 74 68 6F 64 22 3A 20 22  id": 1, "method": "
 50 61 67 65 2E 6E 61 76 69 67 61 74 65 22 2C 20 22 70 61  Page.navigate", "pa
 72 61 6D 73 22 3A 7B 22 75 72 6C 22 3A 20 22 68 74 74 70  rams":{"url": "http
 3A 2F 2F 77 77 77 2E 67 6F 6F 67 6C 65 2E 63 6F 6D 22 7D  ://www.google.com"}
 7D 00 08 00 0D 00 18 00 32 00 3D 00 48 00 65 00 8C 00 AA  }.......2.=.H.e....
 00 B2 00 C9 00 CB 00 D8 00 FF 01 12 00 00 00 00 00 00 02  ...................
 01 00 00 00 00 00 00 00 0F 00 00 00 00 00 00 00 00 00 00  ...................
 00 00 00 00 01 64                                         .....d
ss.recv fd=8 len=6
ws.recv[6]:
 88 80 27 24 F2 9B                                         ..'$..
ws.recv_frame[6]:
 88 80 27 24 F2 9B                                         ..'$..
ws.sending_frame[4]:
 88 02 03 E8                                               ....
ss.remove_fd(8)
wi.send_packet[300]:
 00 00 01 28 62 70 6C 69 73 74 30 30 D2 01 03 02 04 5A 5F  ...(bplist00.....Z_
 5F 73 65 6C 65 63 74 6F 72 5F 10 15 5F 72 70 63 5F 66 6F  _selector_.._rpc_fo
 72 77 61 72 64 44 69 64 43 6C 6F 73 65 3A 5A 5F 5F 61 72  rwardDidClose:Z__ar
 67 75 6D 65 6E 74 D4 05 07 09 0B 06 08 0A                 gument........
 0C 5F 10 1A 57 49 52 43 6F 6E 6E 65 63 74 69 6F 6E 49 64  ._..WIRConnectionId
 65 6E 74 69 66 69 65 72 4B 65 79 5F 10 24 31 31 30 37 42  entifierKey_.$1107B
 34 46 43 2D 41 43 44 38 2D 34 46 31 37 2D 42 33 33 43 2D  4FC-ACD8-4F17-B33C-
 31 33 39 37 32 33 42 37 33 42 45 45 5F 10 1B 57 49 52 41  139723B73BEE_..WIRA
 70 70 6C 69 63 61 74 69 6F 6E 49 64 65 6E 74 69 66 69 65  pplicationIdentifie
 72 4B 65 79 57 50 49 44 3A 32 31 35 5F 10 14 57 49 52 50  rKeyWPID:215_..WIRP
 61 67 65 49 64 65 6E 74 69 66 69 65 72 4B 65 79 10 01 5C  ageIdentifierKey..\
 57 49 52 53 65 6E 64 65 72 4B 65 79 5F 10 24 39 36 32 33  WIRSenderKey_.$9623
 44 31 42 41 2D 37 31 35 36 2D 34 43 30 35 2D 42 31 39 35  D1BA-7156-4C05-B195
 2D 31 41 43 41 46 38 31 41 45 30 35 43 08 0D 18 30 3B 44  -1ACAF81AE05C...0;D
 61 88 A6 AE C5 C7 D4 00 00 00 00 00 00 01 01 00 00 00 00  a..................
 00 00 00 0D 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ...................
 FB                                                        .
ss.recv fd=9 len=4
wi.recv[4]:
 00 00 01 7D                                               ...}
ss.recv fd=9 len=381
wi.recv[381]:
 62 70 6C 69 73 74 30 30 D2 01 02 03 0A                    bplist00.....
 5A 5F 5F 61 72 67 75 6D 65 6E 74 5A 5F 5F 73 65 6C 65 63  Z__argumentZ__selec
 74 6F 72 D3 04 05 06 07 08 09 5F 10 11 57 49 52 44 65 73  tor......._..WIRDes
 74 69 6E 61 74 69 6F 6E 4B 65 79 5F 10 11 57 49 52 4D 65  tinationKey_..WIRMe
 73 73 61 67 65 44 61 74 61 4B 65 79 5F 10 1B 57 49 52 41  ssageDataKey_..WIRA
 70 70 6C 69 63 61 74 69 6F 6E 49 64 65 6E 74 69 66 69 65  pplicationIdentifie
 72 4B 65 79 5F 10 24 39 36 32 33 44 31 42 41 2D 37 31 35  rKey_.$9623D1BA-715
 36 2D 34 43 30 35 2D 42 31 39 35 2D 31 41 43 41 46 38 31  6-4C05-B195-1ACAF81
 41 45 30 35 43 4F 10 89 7B 22 65 72 72 6F 72 22 3A 7B 22  AE05CO..{"error":{"
 63 6F 64 65 22 3A 2D 33 32 36 30 31 2C 22 6D 65 73 73 61  code":-32601,"messa
 67 65 22 3A 22 27 50 61 67 65 27 20 64 6F 6D 61 69 6E 20  ge":"'Page' domain
 77 61 73 20 6E 6F 74 20 66 6F 75 6E 64 22 2C 22 64 61 74  was not found","dat
 61 22 3A 5B 7B 22 63 6F 64 65 22 3A 2D 33 32 36 30 31 2C  a":[{"code":-32601,
 22 6D 65 73 73 61 67 65 22 3A 22 27 50 61 67 65 27 20 64  "message":"'Page' d
 6F 6D 61 69 6E 20 77 61 73 20 6E 6F 74 20 66 6F 75 6E 64  omain was not found
 22 7D 5D 7D 2C 22 69 64 22 3A 31 7D 57 50 49 44 3A 32 31  "}]},"id":1}WPID:21
 35 5F 10 19 5F 72 70 63 5F 61 70 70 6C 69 63 61 74 69 6F  5_.._rpc_applicatio
 6E 53 65 6E 74 44 61 74 61 3A 00 08 00 0D 00 18 00 23 00  nSentData:.......#.
 2A 00 3E 00 52 00 70 00 97 01 23 01 2B 00 00 00 00 00 00  *.>.R.p...#.+......
 02 01 00 00 00 00 00 00 00 0B 00 00 00 00 00 00 00 00 00  ...................
 00 00 00 00 00 01 47                                      ......G
wi.recv_packet[385]:
 00 00 01 7D 62 70 6C 69 73 74 30 30 D2 01 02 03 0A        ...}bplist00.....
 5A 5F 5F 61 72 67 75 6D 65 6E 74 5A 5F 5F 73 65 6C 65 63  Z__argumentZ__selec
 74 6F 72 D3 04 05 06 07 08 09 5F 10 11 57 49 52 44 65 73  tor......._..WIRDes
 74 69 6E 61 74 69 6F 6E 4B 65 79 5F 10 11 57 49 52 4D 65  tinationKey_..WIRMe
 73 73 61 67 65 44 61 74 61 4B 65 79 5F 10 1B 57 49 52 41  ssageDataKey_..WIRA
 70 70 6C 69 63 61 74 69 6F 6E 49 64 65 6E 74 69 66 69 65  pplicationIdentifie
 72 4B 65 79 5F 10 24 39 36 32 33 44 31 42 41 2D 37 31 35  rKey_.$9623D1BA-715
 36 2D 34 43 30 35 2D 42 31 39 35 2D 31 41 43 41 46 38 31  6-4C05-B195-1ACAF81
 41 45 30 35 43 4F 10 89 7B 22 65 72 72 6F 72 22 3A 7B 22  AE05CO..{"error":{"
 63 6F 64 65 22 3A 2D 33 32 36 30 31 2C 22 6D 65 73 73 61  code":-32601,"messa
 67 65 22 3A 22 27 50 61 67 65 27 20 64 6F 6D 61 69 6E 20  ge":"'Page' domain
 77 61 73 20 6E 6F 74 20 66 6F 75 6E 64 22 2C 22 64 61 74  was not found","dat
 61 22 3A 5B 7B 22 63 6F 64 65 22 3A 2D 33 32 36 30 31 2C  a":[{"code":-32601,
 22 6D 65 73 73 61 67 65 22 3A 22 27 50 61 67 65 27 20 64  "message":"'Page' d
 6F 6D 61 69 6E 20 77 61 73 20 6E 6F 74 20 66 6F 75 6E 64  omain was not found
 22 7D 5D 7D 2C 22 69 64 22 3A 31 7D 57 50 49 44 3A 32 31  "}]},"id":1}WPID:21
 35 5F 10 19 5F 72 70 63 5F 61 70 70 6C 69 63 61 74 69 6F  5_.._rpc_applicatio
 6E 53 65 6E 74 44 61 74 61 3A 00 08 00 0D 00 18 00 23 00  nSentData:.......#.
 2A 00 3E 00 52 00 70 00 97 01 23 01 2B 00 00 00 00 00 00  *.>.R.p...#.+......
 02 01 00 00 00 00 00 00 00 0B 00 00 00 00 00 00 00 00 00  ...................
 00 00 00 00 00 01 47                                      ......G
ss.recv fd=9 len=4
wi.recv[4]:
 00 00 01 20                                               ...
ss.recv fd=9 len=288
wi.recv[288]:
 62 70 6C 69 73 74 30 30 D2 01 02 03 12 5A 5F 5F 61 72 67  bplist00.....Z__arg
 75 6D 65 6E 74 5A 5F 5F 73 65 6C 65 63 74 6F 72 D2 04 05  umentZ__selector...
 06 07 5F 10 1B 57 49 52 41 70 70 6C 69 63 61 74 69 6F 6E  .._..WIRApplication
 49 64 65 6E 74 69 66 69 65 72 4B 65 79 5D 57 49 52 4C 69  IdentifierKey]WIRLi
 73 74 69 6E 67 4B 65 79 57 50 49 44 3A 32 31 35 D1 08 09  stingKeyWPID:215...
 51 31 D4 0A                                               Q1..
 0B 0C 0D 0E 0F 10 11 5B 57 49 52 54 69 74 6C 65 4B 65 79  .......[WIRTitleKey
 5A 57 49 52 54 79 70 65 4B 65 79 59 57 49 52 55 52 4C 4B  ZWIRTypeKeyYWIRURLK
 65 79 5F 10 14 57 49 52 50 61 67 65 49 64 65 6E 74 69 66  ey_..WIRPageIdentif
 69 65 72 4B 65 79 55 41 70 70 6C 65 5A 57 49 52 54 79 70  ierKeyUAppleZWIRTyp
 65 57 65 62 5F 10 16 68 74 74 70 73 3A 2F 2F 77 77 77 2E  eWeb_..https://www.
 61 70 70 6C 65 2E 63 6F 6D 2F 10 01 5F 10 1C 5F 72 70 63  apple.com/.._.._rpc
 5F 61 70 70 6C 69 63 61 74 69 6F 6E 53 65 6E 74 4C 69 73  _applicationSentLis
 74 69 6E 67 3A 08 0D 18 23 28 46 54 5C 5F 61 6A 76 81 8B  ting:...#(FT\_ajv..
 A2 A8 B3 CC CE 00 00 00 00 00 00 01 01 00 00 00 00 00 00  ...................
 00 13 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ED     ..................
wi.recv_packet[292]:
 00 00 01 20 62 70 6C 69 73 74 30 30 D2 01 02 03 12 5A 5F  ... bplist00.....Z_
 5F 61 72 67 75 6D 65 6E 74 5A 5F 5F 73 65 6C 65 63 74 6F  _argumentZ__selecto
 72 D2 04 05 06 07 5F 10 1B 57 49 52 41 70 70 6C 69 63 61  r....._..WIRApplica
 74 69 6F 6E 49 64 65 6E 74 69 66 69 65 72 4B 65 79 5D 57  tionIdentifierKey]W
 49 52 4C 69 73 74 69 6E 67 4B 65 79 57 50 49 44 3A 32 31  IRListingKeyWPID:21
 35 D1 08 09 51 31 D4 0A                                   5...Q1..
 0B 0C 0D 0E 0F 10 11 5B 57 49 52 54 69 74 6C 65 4B 65 79  .......[WIRTitleKey
 5A 57 49 52 54 79 70 65 4B 65 79 59 57 49 52 55 52 4C 4B  ZWIRTypeKeyYWIRURLK
 65 79 5F 10 14 57 49 52 50 61 67 65 49 64 65 6E 74 69 66  ey_..WIRPageIdentif
 69 65 72 4B 65 79 55 41 70 70 6C 65 5A 57 49 52 54 79 70  ierKeyUAppleZWIRTyp
 65 57 65 62 5F 10 16 68 74 74 70 73 3A 2F 2F 77 77 77 2E  eWeb_..https://www.
 61 70 70 6C 65 2E 63 6F 6D 2F 10 01 5F 10 1C 5F 72 70 63  apple.com/.._.._rpc
 5F 61 70 70 6C 69 63 61 74 69 6F 6E 53 65 6E 74 4C 69 73  _applicationSentLis
 74 69 6E 67 3A 08 0D 18 23 28 46 54 5C 5F 61 6A 76 81 8B  ting:...#(FT\_ajv..
 A2 A8 B3 CC CE 00 00 00 00 00 00 01 01 00 00 00 00 00 00  ...................
 00 13 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ED     ..................
```

**Comment by nanna481** [comment] 2020-01-16 00:27
Duplicate of # #345
