### ISSUE TITLE
iOS-HybridApp-WEBVIEW-APPIUM: Unable detect webView on real device while it is there

### ISSUE THREAD

**Issue by MaxDomash** [google/ios-webkit-debug-proxy#236] opened 2017-11-10 00:45 UTC
On real device when I do "driver.getContextHandles();" I can see NATIVE_APP only, while webView is there. If, while test is running I manually background the app, launch device Safari browser and foreground the app then I can see NATIVE_APP and WEBVIEW. 

Environment:
Appium version (or git revision) that exhibits the issue: 1.6.5, 1.7.1 and v1.7.2-beta
Last Appium version that did not exhibit the issue (if applicable): -
Desktop OS/version used to run Appium: MacBook Pro (Retina, 13-inch, Early 2015), Processor 2.7 GHz Intel Core i5, Memory 8 GB 1867 MHz DDR3
Node.js version (unless using Appium.app|exe): v6.11.3
Mobile platform/version under test: iPhone 7 iOS 10.3.3
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium CLI
Xcode version set to '9.1'

iOS component webview based - UIWebView.

Appium logs: https://gist.github.com/MaxDomash/d8d346e67931b6db0089f38244346781

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone");
capabilities.setCapability(MobileCapabilityType.UDID, "auto");
capabilities.setCapability("app", "/Users/user/app.ipa");
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 50000);
capabilities.setCapability("startIWDP", true);
capabilities.setCapability("webkitResponseTimeout", "70000");
driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS);

>ios_webkit_debug_proxy 1.8
>Built with libimobiledevice v1.2.0, libplist v2.0.0

**Comment by artygus** [comment] 2017-11-10 11:42
hi @MaxDomash it looks like the duplicate of #199

**Closed by artygus** 2017-11-10 11:42 UTC
